apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ndw7hujp6-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ndw7hujp6-java-quarkus-gitops